// Code generated by protoc-gen-go. DO NOT EDIT.
// source: VendorService.proto

package VendorService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VendorRequestSpecification struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	TvEmac               string   `protobuf:"bytes,3,opt,name=tvEmac,proto3" json:"tvEmac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VendorRequestSpecification) Reset()         { *m = VendorRequestSpecification{} }
func (m *VendorRequestSpecification) String() string { return proto.CompactTextString(m) }
func (*VendorRequestSpecification) ProtoMessage()    {}
func (*VendorRequestSpecification) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b3a2b656e8f5121, []int{0}
}

func (m *VendorRequestSpecification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VendorRequestSpecification.Unmarshal(m, b)
}
func (m *VendorRequestSpecification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VendorRequestSpecification.Marshal(b, m, deterministic)
}
func (m *VendorRequestSpecification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VendorRequestSpecification.Merge(m, src)
}
func (m *VendorRequestSpecification) XXX_Size() int {
	return xxx_messageInfo_VendorRequestSpecification.Size(m)
}
func (m *VendorRequestSpecification) XXX_DiscardUnknown() {
	xxx_messageInfo_VendorRequestSpecification.DiscardUnknown(m)
}

var xxx_messageInfo_VendorRequestSpecification proto.InternalMessageInfo

func (m *VendorRequestSpecification) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *VendorRequestSpecification) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *VendorRequestSpecification) GetTvEmac() string {
	if m != nil {
		return m.TvEmac
	}
	return ""
}

type BrandResponse struct {
	IsSuccessfull        bool     `protobuf:"varint,1,opt,name=isSuccessfull,proto3" json:"isSuccessfull,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=responseMessage,proto3" json:"responseMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrandResponse) Reset()         { *m = BrandResponse{} }
func (m *BrandResponse) String() string { return proto.CompactTextString(m) }
func (*BrandResponse) ProtoMessage()    {}
func (*BrandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b3a2b656e8f5121, []int{1}
}

func (m *BrandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrandResponse.Unmarshal(m, b)
}
func (m *BrandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrandResponse.Marshal(b, m, deterministic)
}
func (m *BrandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrandResponse.Merge(m, src)
}
func (m *BrandResponse) XXX_Size() int {
	return xxx_messageInfo_BrandResponse.Size(m)
}
func (m *BrandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrandResponse proto.InternalMessageInfo

func (m *BrandResponse) GetIsSuccessfull() bool {
	if m != nil {
		return m.IsSuccessfull
	}
	return false
}

func (m *BrandResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

type VendorBrandSpecification struct {
	AppList              []string             `protobuf:"bytes,1,rep,name=appList,proto3" json:"appList,omitempty"`
	SearchColor          string               `protobuf:"bytes,2,opt,name=searchColor,proto3" json:"searchColor,omitempty"`
	FastlaneColor        string               `protobuf:"bytes,3,opt,name=fastlaneColor,proto3" json:"fastlaneColor,omitempty"`
	FocusColor           string               `protobuf:"bytes,4,opt,name=focusColor,proto3" json:"focusColor,omitempty"`
	HasFastlane          bool                 `protobuf:"varint,5,opt,name=hasFastlane,proto3" json:"hasFastlane,omitempty"`
	HasCarousel          bool                 `protobuf:"varint,6,opt,name=hasCarousel,proto3" json:"hasCarousel,omitempty"`
	AboutUsResource      string               `protobuf:"bytes,7,opt,name=aboutUsResource,proto3" json:"aboutUsResource,omitempty"`
	BrandLogoResource    string               `protobuf:"bytes,8,opt,name=brandLogoResource,proto3" json:"brandLogoResource,omitempty"`
	HelpResource         string               `protobuf:"bytes,9,opt,name=helpResource,proto3" json:"helpResource,omitempty"`
	ActivatedStatus      bool                 `protobuf:"varint,10,opt,name=activatedStatus,proto3" json:"activatedStatus,omitempty"`
	Vendor               string               `protobuf:"bytes,11,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string               `protobuf:"bytes,12,opt,name=brand,proto3" json:"brand,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VendorBrandSpecification) Reset()         { *m = VendorBrandSpecification{} }
func (m *VendorBrandSpecification) String() string { return proto.CompactTextString(m) }
func (*VendorBrandSpecification) ProtoMessage()    {}
func (*VendorBrandSpecification) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b3a2b656e8f5121, []int{2}
}

func (m *VendorBrandSpecification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VendorBrandSpecification.Unmarshal(m, b)
}
func (m *VendorBrandSpecification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VendorBrandSpecification.Marshal(b, m, deterministic)
}
func (m *VendorBrandSpecification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VendorBrandSpecification.Merge(m, src)
}
func (m *VendorBrandSpecification) XXX_Size() int {
	return xxx_messageInfo_VendorBrandSpecification.Size(m)
}
func (m *VendorBrandSpecification) XXX_DiscardUnknown() {
	xxx_messageInfo_VendorBrandSpecification.DiscardUnknown(m)
}

var xxx_messageInfo_VendorBrandSpecification proto.InternalMessageInfo

func (m *VendorBrandSpecification) GetAppList() []string {
	if m != nil {
		return m.AppList
	}
	return nil
}

func (m *VendorBrandSpecification) GetSearchColor() string {
	if m != nil {
		return m.SearchColor
	}
	return ""
}

func (m *VendorBrandSpecification) GetFastlaneColor() string {
	if m != nil {
		return m.FastlaneColor
	}
	return ""
}

func (m *VendorBrandSpecification) GetFocusColor() string {
	if m != nil {
		return m.FocusColor
	}
	return ""
}

func (m *VendorBrandSpecification) GetHasFastlane() bool {
	if m != nil {
		return m.HasFastlane
	}
	return false
}

func (m *VendorBrandSpecification) GetHasCarousel() bool {
	if m != nil {
		return m.HasCarousel
	}
	return false
}

func (m *VendorBrandSpecification) GetAboutUsResource() string {
	if m != nil {
		return m.AboutUsResource
	}
	return ""
}

func (m *VendorBrandSpecification) GetBrandLogoResource() string {
	if m != nil {
		return m.BrandLogoResource
	}
	return ""
}

func (m *VendorBrandSpecification) GetHelpResource() string {
	if m != nil {
		return m.HelpResource
	}
	return ""
}

func (m *VendorBrandSpecification) GetActivatedStatus() bool {
	if m != nil {
		return m.ActivatedStatus
	}
	return false
}

func (m *VendorBrandSpecification) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *VendorBrandSpecification) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *VendorBrandSpecification) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *VendorBrandSpecification) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*VendorRequestSpecification)(nil), "VendorService.VendorRequestSpecification")
	proto.RegisterType((*BrandResponse)(nil), "VendorService.BrandResponse")
	proto.RegisterType((*VendorBrandSpecification)(nil), "VendorService.VendorBrandSpecification")
}

func init() { proto.RegisterFile("VendorService.proto", fileDescriptor_8b3a2b656e8f5121) }

var fileDescriptor_8b3a2b656e8f5121 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0xd7, 0xfd, 0xe8, 0xd6, 0xeb, 0x4a, 0x85, 0x81, 0xc9, 0xaa, 0x10, 0x54, 0x11, 0x12,
	0x45, 0x42, 0x19, 0x1a, 0x2f, 0xbc, 0xc2, 0x04, 0xbc, 0x0c, 0x21, 0xa5, 0x94, 0x27, 0x24, 0x70,
	0xdc, 0x4b, 0x1a, 0x29, 0x8d, 0x83, 0xcf, 0xee, 0xdf, 0xc4, 0xbf, 0xc1, 0x7f, 0x86, 0x62, 0x27,
	0x25, 0xe9, 0x86, 0xc6, 0x1e, 0xef, 0xeb, 0xcf, 0xdd, 0xf9, 0xec, 0xef, 0xc1, 0x83, 0xaf, 0x58,
	0x2c, 0x95, 0x9e, 0xa3, 0xde, 0x64, 0x12, 0xc3, 0x52, 0x2b, 0xa3, 0xd8, 0xa8, 0x23, 0x4e, 0x9e,
	0xa6, 0x4a, 0xa5, 0x39, 0x9e, 0xbb, 0xc3, 0xd8, 0x26, 0xe7, 0x26, 0x5b, 0x23, 0x19, 0xb1, 0x2e,
	0x3d, 0x1f, 0xc4, 0x30, 0xf1, 0x19, 0x11, 0xfe, 0xb4, 0x48, 0x66, 0x5e, 0xa2, 0xcc, 0x92, 0x4c,
	0x0a, 0x93, 0xa9, 0x82, 0x9d, 0x41, 0x7f, 0xe3, 0x4e, 0x79, 0x6f, 0xda, 0x9b, 0x0d, 0xa2, 0x3a,
	0x62, 0x0f, 0xe1, 0x28, 0xd6, 0xa2, 0x58, 0xf2, 0x7d, 0x27, 0xfb, 0xa0, 0xa2, 0xcd, 0xe6, 0xfd,
	0x5a, 0x48, 0x7e, 0xe0, 0x69, 0x1f, 0x05, 0xdf, 0x61, 0xf4, 0xae, 0x02, 0x22, 0xa4, 0x52, 0x15,
	0x84, 0xec, 0x19, 0x8c, 0x32, 0x9a, 0x5b, 0x29, 0x91, 0x28, 0xb1, 0x79, 0xee, 0xaa, 0x9f, 0x44,
	0x5d, 0x91, 0xcd, 0x60, 0xac, 0xeb, 0x8c, 0x4f, 0x48, 0x24, 0x52, 0xac, 0xdb, 0xed, 0xca, 0xc1,
	0xaf, 0x43, 0xe0, 0x7e, 0x0a, 0xd7, 0xa7, 0x3b, 0x03, 0x87, 0x63, 0x51, 0x96, 0x57, 0x19, 0x19,
	0xde, 0x9b, 0x1e, 0xcc, 0x06, 0x51, 0x13, 0xb2, 0x29, 0x0c, 0x09, 0x85, 0x96, 0xab, 0x4b, 0x95,
	0x2b, 0x5d, 0x17, 0x6f, 0x4b, 0xd5, 0x45, 0x13, 0x41, 0x26, 0x17, 0x05, 0x7a, 0xc6, 0x0f, 0xd6,
	0x15, 0xd9, 0x13, 0x80, 0x44, 0x49, 0x4b, 0x1e, 0x39, 0x74, 0x48, 0x4b, 0xa9, 0xfa, 0xac, 0x04,
	0x7d, 0xa8, 0x73, 0xf8, 0x91, 0x1b, 0xb6, 0x2d, 0xd5, 0xc4, 0xa5, 0xd0, 0xca, 0x12, 0xe6, 0xbc,
	0xbf, 0x25, 0x1a, 0xa9, 0x7a, 0x0c, 0x11, 0x2b, 0x6b, 0x16, 0x14, 0x21, 0x29, 0xab, 0x25, 0xf2,
	0x63, 0xff, 0x18, 0x3b, 0x32, 0x7b, 0x09, 0xf7, 0xdd, 0x77, 0x5c, 0xa9, 0x54, 0x6d, 0xd9, 0x13,
	0xc7, 0x5e, 0x3f, 0x60, 0x01, 0x9c, 0xae, 0x30, 0x2f, 0xb7, 0xe0, 0xc0, 0x81, 0x1d, 0xcd, 0xf5,
	0x96, 0x26, 0xdb, 0x08, 0x83, 0xcb, 0xb9, 0x11, 0xc6, 0x12, 0x07, 0x77, 0xc3, 0x5d, 0xb9, 0xe5,
	0x97, 0xe1, 0xcd, 0x7e, 0x39, 0x6d, 0xfb, 0xe5, 0x0d, 0x0c, 0xa4, 0xc6, 0x2a, 0xfd, 0xad, 0xe1,
	0xf7, 0xa6, 0xbd, 0xd9, 0xf0, 0x62, 0x12, 0x7a, 0xc3, 0x86, 0x8d, 0x61, 0xc3, 0x2f, 0x8d, 0x61,
	0xa3, 0xbf, 0x70, 0x95, 0x69, 0xcb, 0x65, 0x9d, 0x39, 0xbe, 0x3d, 0x73, 0x0b, 0x5f, 0xfc, 0xde,
	0x87, 0xee, 0x8a, 0xb0, 0x12, 0xce, 0x3e, 0xa2, 0xa9, 0xb5, 0x8e, 0x73, 0x5e, 0x84, 0xdd, 0x0d,
	0xfb, 0xf7, 0xa2, 0x4c, 0x9e, 0xdf, 0x88, 0x5e, 0x77, 0x63, 0xb0, 0xf7, 0xaa, 0xc7, 0x7e, 0xc0,
	0xa3, 0x08, 0xd3, 0x8c, 0x0c, 0xea, 0xcf, 0x7a, 0xe1, 0xae, 0xe6, 0x48, 0xf6, 0xbf, 0x55, 0x26,
	0x8f, 0x77, 0xc0, 0xce, 0x7a, 0x05, 0x7b, 0xec, 0x1b, 0x8c, 0x17, 0x45, 0xd3, 0xc3, 0xd7, 0xbe,
	0xc3, 0x30, 0xb7, 0x54, 0x8f, 0xfb, 0xee, 0x89, 0x5f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x63, 0x5c, 0x92, 0x81, 0x04, 0x00, 0x00,
}
